add clang-format check (#2)

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -18,6 +18,25 @@ jobs:
           architecture: 'x64'
       - run: pip install black
       - run: black --check
+  lint-clang-format:
+    name: lint (clang-format)
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v1
+        with:
+          fetch-depth: 1
+      - uses: actions/setup-python@v1
+        with:
+          python-version: '3.8.x'
+          architecture: 'x64'
+      - run: sudo apt-get update
+      - run: sudo apt-get install -y clang-format-9
+      - run: clang-format-9 --version
+      - run: |
+          if clang-format-9 --output-replacements-xml --style=file $(find fastcountvectorizer -name '*.cpp') $(find fastcountvectorizer -name '*.h') | grep -q '<replacement '; then 
+            echo "clang-format failed"
+            exit 1
+          fi
   test:
     runs-on: ubuntu-latest
     strategy:
